### ISSUE TITLE
Compatibility of the compact II adapter plug and the API

### ISSUE THREAD

**Issue by toony1906** [BoschSmartHome/bosch-shc-api-docs#110]
I have a Smart Home Controller I and an Smart Plug Compact II in operation and wanted to know whether the Smart Plug Compact II is supported by the API at all or whether these are just the “old” Smart Plugs Compact I.

**Comment by sebastianharder** [comment]
There is no such device "Plug Compact II". You probably just have a "Plug Compact".

**Comment by toony1906** [comment]
@sebastianharder I probably didn't express myself correctly. I wanted to know whether the new compact adapter plug, which is for the Smart Home Controller 2, is supported by the API or only the old adapter plug for the Smart Home Controller.

Best regards

**Comment by sebastianharder** [comment]
@toony1906, sorry, I still don't know which "new compact adapter plug" you are referring to. Do you have a link?

**Comment by toony1906** [comment]
@sebastianharder No Problem, the left one is the „old“ one and right is the „new“ one. I just want to know if the right one is supported by the API and with which SHC Generation.
![IMG_0866](https://github.com/user-attachments/assets/6156864b-3ba3-4cc7-acfa-1396be0708e8)

**Comment by david-pace** [comment]
The right one ist just called [Plug Compact](https://www.bosch-smarthome.com/uk/en/products/devices/plug-compact/), not Plug Compact II. I don't know the left one but it seems to be some older model not called "compact".

I can confirm that I use Plug Compact (the right one) with the Smart Home Controller I and that the API also works 👍

**Comment by toony1906** [comment]
@david-pace Perfect, that was the information I needed. Thank you
