### ISSUE TITLE
GET PUT {{shc_api}}/devices/{{device_id}}/services/RoomClimateControl/state

### ISSUE THREAD

**Issue by ilja-stas** [BoschSmartHome/bosch-shc-api-docs#114]
Hi Bosch-folks,

{{shc_api}}/devices/{{device_id}}/services/RoomClimateControl/state that is not working for me. I have Bosch Smart Home Radiator Thermostat II. It's also not working from Postman. I can get the current temperature. But I cannot read and set the desired temperature. I get:
`Response Body: {"@type":"JsonRestExceptionResponseEntity","errorCode":"ENTITY_NOT_FOUND","statusCode":404}`

Everything else is working but if call avalaible services with 
`{shc_api}/smarthome/devices/{device_id}/services`
I also don't see this service.

Is there a bug or I'm doing something wrong?

**Comment by sebastianharder** [comment]
The deviceId of the virtual RoomClimateControl looks like this: roomClimateControl_hz_1

**Comment by ilja-stas** [comment]
Thanks that worked finally. But it's not intuitive.
I got the deviceId via url = f"{shc_api}/smarthome/devices":
Response:
```
 "@type": "device",
        "rootDeviceId": "64-da-a0-40-d9-7e",
        "id": "roomClimateControl_hz_3",
        "deviceServiceIds": [
            "ThermostatSupportedControlMode",
            "TemperatureLevelConfiguration",
            "RoomClimateControl",
            "TemperatureLevel"
        ],
        "manufacturer": "BOSCH",
        "roomId": "hz_3",
        "deviceModel": "ROOM_CLIMATE_CONTROL",
        "serial": "roomClimateControl_hz_3",
        "iconId": "icon_room_bathroom_rcc",
        "name": "-RoomClimateControl-",
        "status": "AVAILABLE",
        "childDeviceIds": [
            "hdm:ZigBee:30exxxxxx289fa"
        ],
        "supportedProfiles": [],
        "installationTimestamp": 0
    }
```

get and put is working that via:
device_id = "roomClimateControl_hz_3" 
url = f"{shc_api}/smarthome/devices/{device_id}/services/RoomClimateControl/state"
