### ISSUE TITLE
Question: Maximum number of requests 

### ISSUE THREAD

**Issue by UEIMBrady** [BoschSmartHome/bosch-shc-api-docs#16]
Hi, I know long polling is encouraged, but what's the actual disadvantage of short polling? There doesn't seem to be rate limiting, is that a change that we should expect? Or is it simply to preserve battery?

**Comment by cap-rb** [comment]
Hi, the main disadvantages of short polling is that you won’t get state changes in time and it could also happen that you miss some state changes during a short polling time period. That won’t happen with the long polling mechanism. Finally, it is more efficient to use the long polling mechanism.

And don’t worry, you only discharge the battery additionally when you change a state on that edge device, but not by requesting it.

Hope this answers your question

**Comment by UEIMBrady** [comment]
Awesome, thank you :)
