### ISSUE TITLE
iOS Widget open doors/windows

### ISSUE THREAD

**Issue by JB1985** [BoschSmartHome/bosch-shc-api-docs#17]
Hello, 

is it possible to read the information from the ios widget "Open doors/windows" with the API?

If yes, how?

![IMG_5648](https://user-images.githubusercontent.com/9932751/70889892-ef3cd500-1fe3-11ea-870d-1d1c10e3e24b.jpg)

**Comment by philbuettner** [comment]
Hi JB, 

the widget is computing the status by 

1. requesting all Door/Window-Contact services with
https://192.168.0.10:8444/smarthome/devices/{deviceId}/services/ShutterContact 

2. and evaluating if the value is set to "OPEN"

Hope that helps!
Phil

**Comment by JB1985** [comment]
OK thanks. I thought there would be a fixed scenario as than to check all individually.

**Comment by philbuettner** [comment]
Well, you could get all services at once with:
https://192.168.0.10:8444/smarthome/services

And then check each service for the serviceId "ShutterContact" with value set to "OPEN". But yes, you need to check each service individually.

**Comment by philbuettner** [comment]
Hi JB1985,

we added an API function to the Postman Collection v0.5. Now you are able to GET open door and window states of all related devices at once with the following request:
`{{shc_api}}/doors-windows/openwindows`

Happy testing,
Phil
