### ISSUE TITLE
Setup | CRT Files 

### ISSUE THREAD

**Issue by Feedy4000** [BoschSmartHome/bosch-shc-api-docs#21]
Hello, 

i am trying to setup the system. 
I do not have the certificate and key to add in postman. 
Where can i get this from?

**Comment by tschamm** [comment]
Hi,

you have to generate your own certificate/key pair. There is no description given in the [readme](https://github.com/BoschSmartHome/bosch-shc-api-docs/blob/master/postman#import-the-collection-the-environment-the-certificate-and-the-key-into-postman), but you can use as an example this [script](https://github.com/tschamm/boschshcpy/blob/master/examples/certificate.py).

**Comment by philbuettner** [comment]
Hi Feedy4000,

with openssl you can create a key-pair with the following command:
`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout shc-key.pem -out shc-cert.pem`

Kind regards,
Phil

**Comment by philbuettner** [comment]
I provided the information how to generate a key pair to the documentation. If this is not working for you, please reopen this issue.
