### ISSUE TITLE
Get the humidity state of a thermostat and a twinguard

### ISSUE THREAD

**Issue by jensflorian** [BoschSmartHome/bosch-shc-api-docs#28]
Version 9.16 has introduced relative humidity to room thermostats and twinguard, which are now shown in the room view of the app.  How do you get these states within the REST API?

**Comment by philbuettner** [comment]
Hi jensflorian,

currently you can only request the humidity of a twinguard with
`/devices/hdm:ZigBee:[id]/services/AirQualityLevel/state`
(see https://apidocs.bosch-smarthome.com/local/ -> Twinguard)

Kind regards
Phil

**Comment by jensflorian** [comment]
Hi Phil,
thanks for the response. I own only room thermostats. Hopefully humidity state for these will be available soon.
Kind regards
jensflorian

**Comment by philbuettner** [comment]
Hi Jens,

ok I will add this point to our feature requests and reopen it. If we have this feature available, I will let you know via this issue. Unfortunately I can't tell you right now, when this will happen.

Kind regards,
Phil

**Comment by philbuettner** [comment]
Hi Jens,

could you please check the following:
GET -> {{shc_api}}/devices/{{id of your wall thermostat}}/services/HumidityLevel/state

Thank you in advance!
Phil

**Comment by philbuettner** [comment]
Ok, meanwhile I was able to test it by myself and it is already available in the production version. I will update the documentation regarding the wall thermostat soon. 

If you have any further questions, please let me know.

Kind regards
Phil

**Comment by jensflorian** [comment]
I had to use GET -> {{shc_api}}/**smarthome**/devices/{{id of your wall thermostat}}/services/HumidityLevel/state which returned
`{
    "@type": "humidityLevelState",
    "humidity": 38.0
}`
and for services
`    {
        "@type": "DeviceServiceData",
        "id": "HumidityLevel",
        "deviceId": "hdm:HomeMaticIP:3014F711A000289A185B21CB",
        "state": {
            "@type": "humidityLevelState",
            "humidity": 38.0
        },
        "path": "/devices/hdm:HomeMaticIP:3014F711A000289A185B21CB/services/HumidityLevel"
    },`

So, yes it is already available (and hopefully soon also accessible through node-red-contrib-bosch-shc). 

Thank you for looking into this.
Kind regards
jensflorian

**Comment by philbuettner** [comment]
The documentation is now up2date:
https://apidocs.bosch-smarthome.com/local/ -> Wall Thermostat
