### ISSUE TITLE
no connection after successfully paired

### ISSUE THREAD

**Issue by hassfers** [BoschSmartHome/bosch-shc-api-docs#29]
Hi,
I got a 201 after paring with a token and a url. 
But I can't access anything excluded the public info. 

do i have to put the token in the header or what I have to do to acces the device list or anything else ? 

Thx

**Comment by tschamm** [comment]
Have you tried to change to port to 8444 after registration?

**Comment by hassfers** [comment]
I use the postman collection from Bosch. There are the port included in the urls I think.
But I looked it up. 
The complete url is:
https://{{host}}:8444/smarthome/devices 

Postman always says it didn't  get any response.

**Comment by philbuettner** [comment]
Hi hassfers, 

did you disbaled the SSL Verification and added the certificate and key for the communication to postman?

Kind regards,
Phil

**Comment by hassfers** [comment]
Hello, 
yes I disabled SSL Verification, but I found out that I only added cert for communication with port 8443 not for port 8444. 
Sorry and many thanks for your very fast help. 

Regards 
Stefan
