### ISSUE TITLE
Local API to access pictures from a camera

### ISSUE THREAD

**Issue by andreaskulicke** [BoschSmartHome/bosch-shc-api-docs#30]
Hi,

it would be very nice to add some API to grab a picture from the Smart Home Eyes camera. It could be integrated in some other automation software like openhab.

Additionally it would be perfect to add  a web hook to get notified on detected movements.

Thanks

**Comment by philbuettner** [comment]
Hello Andreas, 

we already have this wish in our list of feature requests. Unfortunately, I cannot answer at the moment when we will expand the API documentation regarding these points.
But as soon as I know more, I'll write it here in this issue. I'm sorry I can't tell you anything more right now.

Kind regards
Phil

**Comment by dk1959** [comment]
+1

In my case, I would like to access a picture/video from the 360 Indoor Camera via API

Thanks in advance!

**Comment by StupidCoder** [comment]
+1

I'd also be very interested in accessing live images / videos, as well as previous events of both the 360 Indoor and Eyes outdoor camera.

**Comment by NilsGrunwald** [comment]
+1
Essential feature that should be made available asap. Other products on the market already provide such feature "out of the box".

**Comment by Amok1983** [comment]
+1
Essential features from my point of view:
- access to live view 
- access to stored events of the Eyes outdoor CAM
- disable / enable notification function

**Comment by mcfly4711** [comment]
I'd also be very interested in accessing live images / videos, as well as previous events of both the 360 Indoor and Eyes outdoor camera.

**Comment by jo-me** [comment]
+1
Camera should be usable completely without cloud and integrateable with other solutions (Home Assistant, Zoneminder, etc.)

**Comment by devhopsde** [comment]
+1

**Comment by MexXxo** [comment]
+1

**Comment by WernerXXL** [comment]
+1
I'd also be very interested in accessing live images / videos Over a local  url

**Comment by StupidCoder** [comment]
It has been almost a year since this topic started.
Could we please have some feedback from a Bosch employee?
Without API access, the cameras remain a walled garden that does no longer fit into the rest of my smarthome system. I'd really like to keep these cameras, but without API access I will have to throw them out soon.

**Comment by dominicstellwag** [comment]
+1
Is there any progress or prospective timeline on this issue?

**Comment by dominicstellwag** [comment]
+1
Is there any progress or a prospective timeline on this issue?

**Comment by Intelligenzbestie** [comment]
+1, would be interested as well (FHEM / HomeAssistant) - thanks.

**Comment by zygotic99** [comment]
+1 - would have ordered one today if this was available

Even an endpoint to get the current snapshot as a jpeg would be a good step. Full open and local API that can notify or be polled by a smarthome system even better.

**Comment by JanZimmer** [comment]
+1, and it would be absolutely awesome if the information about the position of movement would be available. as well

**Comment by benny000004** [comment]
+1 People are now waiting over 1 year for a response. Now the camera is on sale, so that it would be nice to get a little more information about a roadmap or similar for the Local API access. Thank you!

**Comment by MexXxo** [comment]
@philbuettner any update? Is it still on the list, can we expect access this year or will it probably take more time?

**Comment by StupidCoder** [comment]
@MexXxo , according to LinkedIn @philbuettner left Bosch last September. It feels like since then nobody at Bosch claimed responsibility here. I'm deeply disappointed by their lack of communication.

**Comment by MexXxo** [comment]
@StupidCoder let's be patient. They probably have to reorganize a bit. I hope they can provide us a rough timeline to see if the cameras are dev friendly or not.

**Comment by philbuettner** [comment]
Hi, yes it's true, I no longer work at Bosch Smart Home. But it's not entirely true that no one has taken responsibility. I think @sebastianharder is doing a very good job here. I am sure he will post a comment as soon as there are any news regarding this topic. But I think it's still a matter of prioritization. Personally, I also want to have a local api access to implement this into my private smart home project. But I can understand that having to wait here for so long is somehow unsatisfactory.

**Comment by cap-rb** [comment]
Hello @all,

Sorry for taking so long... 
We have discussed your requirements within the team and came to the conclusion that we currently have no API for accessing the camera locally, since in the current implementation everything works over the cloud. 
Unfortunately, we cannot provide the Local API documentation you have requested for. There is also no plan to provide local access to the camera in the near future.

**Comment by mback2k** [comment]
What about opening up the cloud-based API? I would love to be able to use the camera with e.g. [Home Assistant](https://www.home-assistant.io/).

**Comment by MexXxo** [comment]
@cap-rb thanks for the clear statement even if it is not the answer we wanted to hear. I guess this is also valid for direct local access to the camera right?

So I will sadly have to look for another camera solution.

**Comment by devhopsde** [comment]
Guys, this is really bad! Bosch Smart Home is one of few solutions, that can run locally (partially). With the Camera (as an essential part of the security system) not providing any API, the whole system cannot be used..
So I will sadly have to look for another camera, smoke detector, smart plugs, etc.

**Comment by mcfly4711** [comment]
Really bad. I will also search an alternative solution for camera, smoke detectors, water sensor... :-(

**Comment by Amok1983** [comment]
Most of you (me as well) have already bought the not so smart Bosch smart Cam. I think they will not give anything about our complains. Wirh a good reason: they already got our Money...

**Comment by oli-d** [comment]
> Most of you (me as well) have already bought the not so smart Bosch smart Cam. I think they will not give anything about our complains. With a good reason: they already got our Money...

So you bought something that didn't have the feature you were looking for. And now you complain that it doesn't have the feature you were looking for and unfortunately never will???

What a strange world we are living in...

**Comment by Amok1983** [comment]
Not completly right. I bought 3. 😅

The features are ok, but could be much better.
So it is more or less a dumb stand alone device.

**Comment by oli-d** [comment]
> Not completly right. I bought 3. 😅
> 
> The features are ok, but could be much better.
> So it is more or less a dumb stand alone device.

😂

I totally share your pain and also hoped for much better news, but it really looks as if the vast majority of consumers don't give a damn about this topic. So there's no real need for companies to invest in it 😢

**Comment by moshemalawach** [comment]
Cool, was going to buy one and found this topic. Out of my shopping list!

**Comment by Amok1983** [comment]
Good decision!

**Comment by StupidCoder** [comment]
It still boggles my mind that Bosch wastes this opportunity. As some here
wrote, the hardware is great. But the app is still flaky and the fact that
it's impossible to integrate with other systems ruins it completely.

Am Mi., 9. Feb. 2022 um 13:54 Uhr schrieb Amok1983 ***@***.***

**Comment by kulmann** [comment]
> Cool, was going to buy one and found this topic. Out of my shopping list!

Same for me, couldn't agree more. I have everything related to heating by Bosch. After reading this I'll buy elsewhere for topics safety and security.

**Comment by felix-schwarz** [comment]
I was just looking for a suitable device for a project - and the Bosch Smart Eyes looked good. But having no local API access now or in the foreseeable future, I need to keep looking for alternatives that do offer that.

**Comment by f-track** [comment]
I have two of these and im very sad to hear this.

Its not running good in the "normal" Bosch Smart Home App and without api and cloud based services it is trash.

Very expensive trash.
Please don't buy products like this...

best regards

**Comment by devhopsde** [comment]
Is there any update on this topic? I am thinking about removing all the bosch parts as soon as the batteries in my smoke detectors are empty.

**Comment by mosandlt** [comment]
Is there any news ?
