### ISSUE TITLE
SSL issues on port 8443 and 8444

### ISSUE THREAD

**Issue by patrickvogel** [BoschSmartHome/bosch-shc-api-docs#33]
Hi,

I followed the instructions on "How to use the Bosch Smart Home Postman Collection". 
The public information request (https://{{host}}:8446/smarthome/public/information) works as expected. 

But as soon as I send the request to create a new client (Port 8443), I get the following response:

"Could not get any response
There was an error connecting to https://192.168.178.36:8443/smarthome/clients.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General"

The SSL certificate verification is turned off and there is no proxy. The same error appears when requesting anything on port 8444.

Here is the output of the public information json:
```
{
    "apiVersions": [
        "1.0"
    ],
    "softwareUpdateState": {
        "@type": "softwareUpdateState",
        "swUpdateState": "NO_UPDATE_AVAILABLE",
        "swUpdateLastResult": "UPDATE_SUCCESS",
        "swUpdateAvailableVersion": "",
        "swInstalledVersion": "9.16.1457-11868",
        "swActivationDate": {
            "@type": "softwareActivationDate",
            "timeout": 604800000
        }
    },
    "claimed": true,
    "country": "DEU",
    "tacVersion": "DEU-10",
    "shcIpAddress": "192.168.178.36",
    "clientIds": [
  // manually removed client ids //
    ],
    "featureToggles": {
        "http-rest.api": false,
        "app-store-rating.ios": true,
        "water-leakage-sensor.pairing": false,
        "siri-shortcuts": false,
        "app-logging": false,
        "app-analytics": false,
        "shading.slats.values": false,
        "plugcompact.pairing": false,
        "cameras.extension": true,
        "shading.advance.menu": true,
        "app-store-rating.android": true,
        "homekit-activation": false,
        "whitegoods.pairing": true,
        "plug.automation.condition.onoff": false,
        "cloud.tokenvalidation": true,
        "hue.automation.condition.onoff": false
    },
    "connectivityVersions": [
        {
            "name": "claiming",
            "minVersion": 1,
            "maxVersion": 1
        },
        {
            "name": "noncePairing",
            "minVersion": 1,
            "maxVersion": 1
        },
        {
            "name": "buttonPairing",
            "minVersion": 1,
            "maxVersion": 1
        }
    ]
}
```

What could be the problem? The http-rest.api-setting (false) looks suspicious, but I have no idea how to toggle it.

Thanks in advance,
Patrick

**Comment by philbuettner** [comment]
Hi Patrick,

the feature toggle 'http-rest.api' has nothing to do with this. To add a client port 8443 is correct. As you mentioned you disabled the SSL verification. But you didn't mention whether you pressed the button of your SHC before adding a client. Also try to set the request timeout to 0 to never time out. 

Hope that helps!
Phil

**Comment by philbuettner** [comment]
Hi Patrick,

I assume that you were able to solve the problem. If you still have problems, then just drop me a line here. 

Kind regards,
Phil
