### ISSUE TITLE
Stop the shutter control via API request

### ISSUE THREAD

**Issue by coeing** [BoschSmartHome/bosch-shc-api-docs#34]
Hi there!

First of all thanks for the nice clean Rest API for your controller. It's easy too understand and to use. A special thanks for the step-by-step guides to get it running and the Postman files :)

Right now I am working together with a few other voluntary devs to develop a binding for your Smart Home devices for openHAB (https://www.openhab.org/).

https://github.com/stefan-kaestle/openhab2-addons 

I am currently working on the shutter control handling. Moving the shutters up and down and setting a specific open ratio was easy enough to implement.

But what I am missing is a command to stop the shutters with an API request. As a workaround I tried to get the current state and set it immediately, but I get back the target state of the shutter rather than the current state.

Would be great to have a separate API endpoint for this. Or is it maybe possible already but not documented?

**Comment by tschamm** [comment]
Hi, the API command is available but I assume it is missing in the docs. In my home assistant binding, I use the following command:
PUT /devices/{deviceId}/services/ShutterControl/state with the json payload 
{
  „@type“: „shutterControlState“,
  „operationState“: „STOPPED“
}
Good luck!

**Comment by coeing** [comment]
Alright, in an attempt to work around it I tried to send "operationState": "STOPPED" to the shutter control and it worked :) 

It's not documented though, so I would be happy if you could confirm that this is the way to do it and add the "operationState" field to the documentation: https://apidocs.bosch-smarthome.com/local/#/States/put_devices__deviceId__services_ShutterControl_state

**Comment by coeing** [comment]
@tschamm Thanks! I had my browser tab still open, so I didn't see your answer before writing my comment. But we obviously came to the same solution ;)

**Comment by philbuettner** [comment]
Hi coeing,

we are happy that activities are taking place on the OpenHAB front. 

The request, as @tschamm describes, to stop a shutter is correct. I will update the documentation regarding this point soon.

If you have any further questions, do not hesitate to open a new issue.

Kind regards
Phil
