### ISSUE TITLE
Thermostat API to set desired temperature

### ISSUE THREAD

**Issue by coeing** [BoschSmartHome/bosch-shc-api-docs#35]
Hi there,

The shutter control binding for openHAB is complete, thanks for helping with issue #34 :)

I am now working on the binding for the thermostats. The getters for the temperature and the valve tappet are well documented and are no problem.

But I wonder if there is a way to set the desired temperature on a thermostat. As it is possible via the Bosch Home app I hope it is just missing in the documentation as well.

**Comment by philbuettner** [comment]
Hi coeing,

you can set the temperature via the room climate control. It is described in the [OpenAPI documentation](https://apidocs.bosch-smarthome.com/local/) -> ClimateControl.

Hope that helps,
Phil

**Comment by coeing** [comment]
Hi @philbuettner ,

Thanks for the super quick answer :) I tried that, but I got an error response:
```
{
    "@type": "JsonRestExceptionResponseEntity",
    "errorCode": "ENTITY_NOT_FOUND",
    "statusCode": 404
}
```

I send the PUT request to the thermostat device itself, was that correct?

**Comment by coeing** [comment]
Oh, I see, there are extra "virtual" devices for the rooms the thermostats are in. I can work with that, thanks a lot!

**Comment by philbuettner** [comment]
Yes, right, you can only set the temperature for  the entire room and not for individual devices. If you want to do this, you have to separate them into individual rooms.
