### ISSUE TITLE
Smart Garden API?

### ISSUE THREAD

**Issue by eavanvalkenburg** [BoschSmartHome/bosch-shc-api-docs#36]
Hi, this is a great resouce for smart home by Bosch, but is there something similar for the Smart Garden by Bosch (Indego mowers), I'm involved in building an integration for indego mowers and would like to build on top of official documentation rather than reverse engineering!

**Comment by philbuettner** [comment]
Hi eavanvalkenburg, 

at the Bosch Developer Portal you can find all official public APIs of Bosch devices and services:
https://developer.bosch.com/

However, I fear that smart gardening is not yet represented there. 

But try searching the web for: API for Bosch Indego Connect 

Kind regards
Phil

**Comment by eavanvalkenburg** [comment]
The reason I asked is that it isn't there and I can't find any public references for it either!

**Comment by philbuettner** [comment]
I am very sorry but I can not help you on this topic. Finally you could call the support of Bosch Smart Gardening.

**Comment by eavanvalkenburg** [comment]
Ok!
