### ISSUE TITLE
Somfy API integration into the Bosch Home Control System

### ISSUE THREAD

**Issue by MrDevGuy2K** [BoschSmartHome/bosch-shc-api-docs#37]
Hello Bosch Community :)

I am currently trying to integrate my Somfy IO rolling shutters into the Bosch Home Control System. Unfortunately, I haven't found the right approach yet, so I'm asking you for help. The Somfy API can be found here: https://developer.somfy.com/apis-docs

As I currently understand it, I can communicate via REST API between the Bosch API and the Somfy API. I have already created an "app" in the Somfy portal.

Do any of you already have experience with integrating Somfy or similar products into the Bosch API?

My ideal is that I can control everything from my smartphone via the Bosch Client App. For example, if a room gets too warm and a Bosch thermostat reports this, I want to auto lower my rolling shutters via IFTTT etc. as an example scenario.

Thank you very much for your support in advance!

**Comment by hxmelab** [comment]
To do so, follow these steps:
1. Long Poll your SHC:
https://github.com/BoschSmartHome/bosch-shc-api-docs/tree/master/postman#get-events-from-the-bosch-smart-home-controller-long-polling
2. Filter the corresponding device service containing the temperature 
3. Check the temperature value, and if it is too high then
4. Perform an action on your shutter via the Somfy API

Just to avoid a misunderstanding of the concept, you can not integrate one API into another. Instead you write some code, and integrate both APIs into your application. But there are some open source smart home platforms already available having a lot of APIs integrated. Hence, you do not need to code this by yourself.
