### ISSUE TITLE
Integrate option for Webhook (or something similar) whenever a scenario is triggered

### ISSUE THREAD

**Issue by JanZimmer** [BoschSmartHome/bosch-shc-api-docs#38]
It would be very nice to enable the SHC to call a webhook or something similar to push the event of a scenario being triggered to other services. In that way, e.g., the Twist Remote would be much more powerful in advanced setups which involve more than just using the smart phone app on its own.

An example could be as follows:
  On triggering of a scneario
    POST - example.host/example-endpoint
    with body `{scenario: 'scenario name'}`
    and optional http header fields set

**Comment by hxmelab** [comment]
Hi Jan,

you receive a message via the long poller as soon as a scenario was triggered with the scenario id and the name of the scenario.

Hope that helps!

**Comment by hxmelab** [comment]
By the way, if you do not receive a message, check if your client id, starts with: oss_

**Comment by JanZimmer** [comment]
Thanks for the clarification. I do not find the documentation of the returned entities of long polling. Could you tell me where to find it?

**Comment by hxmelab** [comment]
These are more or less the same JSONs as the responses of the REST calls.
