### ISSUE TITLE
Unrecognised Certificate?

### ISSUE THREAD

**Issue by stevecrox** [BoschSmartHome/bosch-shc-api-docs#43]
I've created certs following the postman instructions connecting to the public information on port 8446 works without issue (even if I add the certificate to that port). However connections on port 8443 or 8444 result in the following error:

`Error: write EPROTO 8203879879560:error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 46`

I converted the crt/key into a pem and ran the request as curl command (see below) 

`curl -kv --cert ~/Downloads/client/client.pem https://192.168.1.103:8443/smarthome/clients --data '{ "@type": "client", "id": "oss_haas",  "name": "OSS HomeAssistant",  "primaryRole": "ROLE_RESTRICTED_CLIENT",  "certificate": "-----BEGIN CERTIFICATE-----\r<removed>\r-----END CERTIFICATE-----" }'
`
This resulting in the Bosch Controller responding with:

`*   Trying 192.168.1.103:8444...
* TCP_NODELAY set
* Connected to 192.168.1.103 (192.168.1.103) port 8444 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
Enter PEM pass phrase:
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS alert, certificate unknown (558):
* error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown`

Which suggests the Bosch controller is expecting the certificate to be signed by a known certificate authority and rejecting the request as it's a self signed certificate.

Any thoughts on what I need to do?

**Comment by sebastianharder** [comment]
@stevecrox did you press the button on the Smart Home Controller?

**Comment by MexXxo** [comment]
had a similiar issue and actually I just forgot to press the pairing button on the controller. Probably it would be worth to highlight this step a bit more here in the docs :-)
