### ISSUE TITLE
API 1.x no longer supported after 2021-05-10

### ISSUE THREAD

**Issue by sebastianharder** [BoschSmartHome/bosch-shc-api-docs#46]
Announcement: The Smart Home Controller update scheduled for **May 2021** will no longer support API 1.x. 

**All clients must therefore migrate to API 2.1, which is already available on the Smart Home Controllers.**

The API changes between 1.x and 2.x are mostly marginal, but all requests including an HTTP header with `"api-version : 1.0"` will no longer work.

- New REST APIs for the intrusion detection system need to be added to the Postman collection.
- Removed REST APIs need to be removed from the Postman collection.
- Provide a change log

**Comment by coeing** [comment]
@sebastianharder Does setting the header "api-version" to "2.1" cause problems with controllers that run an older software version? The question came up during our pull request into openHAB (https://github.com/openhab/openhab-addons/pull/10097)

**Comment by sebastianharder** [comment]
@coeing the controllers are forcefully updated. Only very, very few might not have API 2.1 available by now. API 2.1 is available since the controller update in December.
