### ISSUE TITLE
API call to trigger the siren on the smoke detectors

### ISSUE THREAD

**Issue by christschn81** [BoschSmartHome/bosch-shc-api-docs#47]
Hi, is there a way to trigger the siren on the smoke detectors directly? I am not talking about testing the detector but have the siren ring for a specified amount of time. I know there are the builtin mechanisms with your motion detector and app. But in my case I want to reuse my Hue motion detectors to do the job.

Cheers, Christian

**Comment by sebastianharder** [comment]
Hi @christschn81, due to battery life-time that's not possible. Sorry!
