### ISSUE TITLE
Motion Detector – expose current brightness level

### ISSUE THREAD

**Issue by Purii** [BoschSmartHome/bosch-shc-api-docs#49]
Great structured repo, really like the postman collection!

It would be great, if one read the current `lightlevel`. Since it's possible to change the sensitivity of the motion sensor through the app, I guess that there must be some kind of light level information?

**Comment by sebastianharder** [comment]
Unfortunately, the measured brightness level is currently not available in the (public) API. This might change in the future.

**Comment by sebastianharder** [comment]
Added the motion detector illuminance level ("MultiLevelSensor") to the Postman collection in #68.
