### ISSUE TITLE
Ledvance RGBW bulbs do not expose service for setting white color temperature (probably HueColorTemperature)

### ISSUE THREAD

**Issue by JanZimmer** [BoschSmartHome/bosch-shc-api-docs#50]
The Ledvance RGBW Bulbs do not expose the `HueColorTemperature` service via the API so correct setting of white hue (or color temp) is not possible via API, although it is possible via app.

Using the `HSBColorActuator` service does not work either as it only "mixes" white temps via RGB LEDs.

```
{
        "@type": "device",
        "rootDeviceId": "xxx",
        "id": "xxx",
        "deviceServiceIds": [
            "CommunicationQuality",
            "HSBColorActuator",
            "MultiLevelSwitch",
            "BinarySwitch"
        ],
        "manufacturer": "LEDVANCE",
        "roomId": "hz_5",
        "deviceModel": "LEDVANCE_LIGHT",
        "serial": "xxx",
        "profile": "GENERIC",
        "iconId": "icon_philips_roomlightcontrol",
        "name": "Stehlampe mitte",
        "status": "AVAILABLE",
        "childDeviceIds": []
    }
```

Related: https://github.com/tschamm/boschshc-hass/issues/17

**Comment by sebastianharder** [comment]
Hi @JanZimmer,

colored lamps do not expose the `HueColorTemperature` device service on purpose and this is also **not planned** for the future.

Although the Bosch apps allow to change the color temperature of colored lamps, they also use the `HSBColorActuator` device service for this.

**Comment by JanZimmer** [comment]
@sebastianharder all right.
Could you maybe go into detail on how conversion should take place so I get my Ledvance bulbs to **use the white LEDs** even though I use HSBColorActuator?
I wasn't able to do so, yet.

**Comment by hxmelab** [comment]
Hi Jan,

just use the device service HueColorTemperature, e.g.:

@type: "DeviceServiceData"
id: "HueColorTemperature"
deviceId: "hdm:ZigBee:f0d1b8000013d2b0"
@type: "colorTemperatureState"
colorTemperature: 316
colorTemperatureRange: object
minCt: 153
maxCt: 370

With e.g. Postman you could get all available device service of this device.

Hope that helps!

**Comment by JanZimmer** [comment]
@hxmelab this is the whole point of this issue, as for RGBW Ledvance bulbd, this service is not exposed.

**Comment by hxmelab** [comment]
Ok, now I see the problem. Sorry...

**Comment by JanZimmer** [comment]
So to make things worse, I just recognized, that even if I use the app to control the white temperature, the bulbs start to switch between using RGB and White LEDs for different shades of white. 

Is there a magic Lookup table for these bulbs to consistently control the white temperature?

**Comment by JanZimmer** [comment]
Ledvance definitely support the service, btw: https://zigbeealliance.org/zigbee_products/par16-rgbw-value/

**Comment by sebastianharder** [comment]
@JanZimmer we are currently checking how we can support here.

**Comment by JanZimmer** [comment]
Thanks. I contacted the Ledvance guys, as well. They told me, that despite of what is actually advertised, the bulbs are not capable of "true" white tone/hue/temp mixing with actual white LEDs but will also always use the RGB LEDs. Hence there might be no way of providing the Temp related services.

For me this is a impractical solution far away from what other competitors deliver for roughly the same price.
As there is no openly available Backlog for the App, the bigger problem (besides the API related) is the far too basic control mechanisms for lamps in the App (no grouping, no Alexa support besides scenes - really?, cluttered UI for color selection).
