### ISSUE TITLE
Unsubscribe from long polling necessary?

### ISSUE THREAD

**Issue by tschamm** [BoschSmartHome/bosch-shc-api-docs#52]
This is more a question than an issue:
Following the docs, the poll_id is invalidated after 5 minutes of inactivity. Does it matter if I unsubscribe from long polling?Skipping the unsubscribtion step will improve the speed when closing the library.

**Comment by sebastianharder** [comment]
Hi @tschamm, an active subscription caches events on the SHC until they are polled, which consumes memory and could be a potential problem when you have many active subscriptions at the same time. For a single subscription the memory consumption should be negligible. If a mobile phone looses the connection to the SHC, it can also not invalidate its subscription.
