### ISSUE TITLE
States for smoke detector

### ISSUE THREAD

**Issue by stevoboy** [BoschSmartHome/bosch-shc-api-docs#53]
Dear Bosch Team,

what are the states the smoke detector can take in alert mode? In my IOBroker it shows IDLE_OFF. What would be the alarm state?

Thanks!

**Comment by sebastianharder** [comment]
Hi @stevoboy,

there are three more states:

PRIMARY_ALARM, SECONDARY_ALARM and INTRUSION_ALARM,
