### ISSUE TITLE
Log filled with info messages

### ISSUE THREAD

**Issue by stevoboy** [BoschSmartHome/bosch-shc-api-docs#55]
Dear all,

My log is filled with info messages like these:

(13934) State value to set for "bshb.0.openDoorsAndWindows.all.open" has to be stringified but received type "object"

After update to the latest js version. Does anybody else have this?

My whole system seems knocked out by this 

![image](https://user-images.githubusercontent.com/84937873/128601466-4f7f7003-d5bd-4036-b9c9-96f5999fc32b.jpeg)
![image](https://user-images.githubusercontent.com/84937873/128601469-634ec4ed-b6f5-4e31-b4ed-ca1171afccf8.jpeg)

![image](https://user-images.githubusercontent.com/84937873/128601474-91919d3b-6f39-41df-bd2c-fbd06a467863.jpeg)

**Comment by DennisSc** [comment]
Maybe you will receive better (more) answers if you ask your question over at the github repository for the "iobroker bosch smart home bridge" (which is what you seem to be using, guessing from your screenshots).

The logfiles you mention are generated by iobroker resp. the iobroker.bshb adapter, and not by the Bosch REST API...

https://github.com/holomekc/ioBroker.bshb/issues/47

**Comment by stevoboy** [comment]
I guess this issue can be closed. The number of messages went down after updates
