### ISSUE TITLE
Node Red

### ISSUE THREAD

**Issue by Elculione** [BoschSmartHome/bosch-shc-api-docs#57]
Hey, i Hope somebody can help me.
I wants to connect SHC with nodered.
i become the error 401.
witch password i needed, the original from the app...? Its doesnt work..

**Comment by danielstroehmann** [comment]
Yes, it is the system password but before you connect make sure to long-press the button first until the lights start flashing. Then go back to node-red and try connecting.

**Comment by fubian** [comment]
I have a similar issue with the registration of a new device, but I receive an error 400:

```
{
    "@type": "JsonRestExceptionResponseEntity",
    "errorCode": "PROPERTY_VALIDATION_FAILED",
    "statusCode": 400
}
```

It is described in detail in #58
