### ISSUE TITLE
Smart Home Controller: no access to API due to expired certificate.

### ISSUE THREAD

**Issue by jensflorian** [BoschSmartHome/bosch-shc-api-docs#61]
The certificate on the Smart Home controller has expired and API access therefore is no longer working. 

![7E244FDC-5612-4F04-857C-1A3A7667D255](https://user-images.githubusercontent.com/58853392/150634260-0da76ca9-7f16-4fa1-89a7-87b1e872ce2b.jpeg)

How to you update certificates on the controller?

**Comment by cap-rb** [comment]
Please try a Smart Home Controller restart. Afterwards the certificate should be updated.
