### ISSUE TITLE
battery level

### ISSUE THREAD

**Issue by justme-1968** [BoschSmartHome/bosch-shc-api-docs#62]
i have just started the bsh integration for fhem. getting the environmental data for a twinguard works perfectly fine but i' wondering if there is a way to get information about the battery level via the api.

also starting and stopping the test and alarm via the api would be great.

the same goes for silencing at least the group as it seems this is also possible with the bsh app.

as i don't have any of the bidcos based hardware: can the api control this hardware like it is possible with the ccu3 rpc api?

**Comment by hxmelab** [comment]
Please check for battery level:
https://forum.iobroker.net/topic/25370/test-adapter-bshb-bosch-smart-home-v0-0-x/36?lang=en-US

**Comment by justme-1968** [comment]
nearly perfect :)

reading this endpoint works fine. now i have also noticed that the service is included in the services list... it is just missing from the documentation.

do you also happen to know if there are events on the long poll connection for battery faults ?

**Comment by hxmelab** [comment]
Yes, you receive this kind of events via long polling.

**Comment by justme-1968** [comment]
that solves that. thanks!
