### ISSUE TITLE
Update Docu: Systempassword need to be set in the headers!

### ISSUE THREAD

**Issue by rettet-die-stille** [BoschSmartHome/bosch-shc-api-docs#64]
I think the docmentation under https://github.com/BoschSmartHome/bosch-shc-api-docs/tree/master/postman is missing the important instruction that you need to set a header "Systempassword" with the value {{system_password_base64}} if you want to add a new user.

**Comment by tobiastraxel** [comment]
The postman collection uses this header already on the request to add a new client. 
However, it is not possible to register a new client. I always get a 401 response. 
In case I put some invalid base64 code in the header "Systempassword" I get status Code 500.

**Comment by sebastianharder** [comment]
The system password is mentioned in the README and is contained in the "new client" request in the Postman collection.
