### ISSUE TITLE
Update API docs for new devices

### ISSUE THREAD

**Issue by tschamm** [BoschSmartHome/bosch-shc-api-docs#66]
In the last weeks Bosch has released serveral new devices like the `Light / Shutter Control II`, `Smoke Detector II`, `Room Thermostat II`, `Outdoor Siren`, `Door contact II`, `Door Contact II Plus`, and `Thermostat II`. 

It would be great if you can update the API docs to describe all services of the new devices. Otherwise devices/services have to be reverse engineered from Postman, which may affect the stability/quality for Bosch devices in the different open source platforms (home assistant, openhab, iobroker).

**Comment by sebastianharder** [comment]
We will probably find the time to update the documentation around the turn of the year.

**Comment by sebastianharder** [comment]
Hi @tschamm,
we have updated the Postman collection with API 3.2.
If you have any questions, let me know!

The OpenAPI specification still needs to be updated.

Regards,
Sebastian
