### ISSUE TITLE
OpenAPI Link is not working

### ISSUE THREAD

**Issue by holomekc** [BoschSmartHome/bosch-shc-api-docs#70]
Hi team,

when clicking on the link to the OpenAPI Documentation from the Readme file, I just receive an error message from you CloudFront -> S3 setup with Access Denied.

Can you please take a look.

Br,
Chris

**Comment by hxmelab** [comment]
Please fix:
https://apidocs.bosch-smarthome.com/local/

Thank you!

**Comment by sebastianharder** [comment]
It's located here now: https://local.apidocs.bosch-smarthome.com/
