### ISSUE TITLE
Bosch Smart Home Basis/Bridge/Controller 2 in Iobroker ?

### ISSUE THREAD

**Issue by Matzeonom** [BoschSmartHome/bosch-shc-api-docs#71]
Hi All,

after exchange of Controller Ver.1 to the new Ver.2 I ran into trouble.
Neither Google was able to help, nor every solution posted so far on Ver.1 worked out.
No chance to connect Controller II to Iobroker. 
Classical message: Start pairing. Activate pairing on Bosch Smart Home Controller by pressing button until flashing.

Anybody suffering from the same ? Furthermore: Any solutions ??

Thanks in advance

**Comment by tschamm** [comment]
Did you try to press the button just shortly?
