### ISSUE TITLE
PROPERTY_VALIDATION_FAILED

### ISSUE THREAD

**Issue by pinnaclebet** [BoschSmartHome/bosch-shc-api-docs#72]
Hello,

I try to pair a new client. Button pressed. Request below. But always get 
{
    "@type": "JsonRestExceptionResponseEntity",
    "errorCode": "PROPERTY_VALIDATION_FAILED",
    "statusCode": 400
}
What is wrong? Please help.

Request:
{
  "@type": "client",
  "id": "oss_Test",
  "name": "OSS Test",
  "primaryRole": "ROLE_RESTRICTED_CLIENT",
  "certificate": "-----BEGIN CERTIFICATE-----/rMIIDbTCCAlWgAwIBAgIUQXWQFFWC1L4MZdQGDqMqeP2mH4owDQYJKoZIhvcNAQELBQAwRTELMAkGA1UEBhMCREUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAgFw0yMzAxMjYyMTE1NTNaGA8yMDUwMDYxMjIxMTU1M1owRTELMAkGA1UEBhMCREUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAN1jX8vsVOuyZ239b0xJRq1ttYaL9+qNLXYfRaoJj6DAHl6fB1QUGsHOdmtvLtRn9sh7NPdbpG7RhiYCUNxAXvLIN7tO+64isGQ7lEYmsYkcXBqOD8sP+F1l/j5q+loqxm4nFkeXelda/UgwLCtxKp32+hX4XC4N/4lwhloZ4Kmive4GaNxQ2+q0IpEFDUVUAbwJxy+22QtO88nT4JYjfOQaV18Z7tZgpwwAqJdmIlVUMLmC4mjJ0WcAwdsa3GdAprDyP1PKVBU+EZNG0k1ebhsxLDm1pwFRKSyyjVMyugK8p5Qy9whYCDFzS/1KThQ9SwELR6arWgLm1GJmHSY6dNsCAwEAAaNTMFEwHQYDVR0OBBYEFAJeavp+Yjn6pJttIqBG497NII7wMB8GA1UdIwQYMBaAFAJeavp+Yjn6pJttIqBG497NII7wMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAEd0muTwqp6iaiXtFFXVdOOIoPMXPIXqFIJyychzz+5QV5sXCMhOIGmZWnOe0q5fdRvPw+NqSHprMEWebYVkJLFEYe+UrQBM3JetmFCPGlcWHr/p0EpHE7HKwFttS1E3CrjUXAaAzvj7Bf6v9XVNlQxKs0obPtskX+ANIKxqWog0CqLHlhVKfo1qYcBxji/g/OkkcLvR64GAgfrTJrLMNbkiPJpm6dbNk05MChXOpWadDtvX7npldf9jBf3g4YngzgoLso27oke3g7kcCmAmWJsHWiD2hS9DwFZ563nU+2Id7nWQW7R7dDkyTiF4IP+RMyuCmCN3ie/+tseQfPYrs3o=/r-----END CERTIFICATE-----"
}

**Comment by sebastianharder** [comment]
Did you add a new line after "-----BEGIN CERTIFICATE----"?

**Comment by pinnaclebet** [comment]
A carriage return (/r) has been already added at the beginning and end (see above)
-----BEGIN CERTIFICATE-----/r

my suspicion is that the manual carriage return removal from the certificate did not work. Several methods tried, tools tried, but always same error message as indicated

**Comment by jakobgoerke** [comment]
use a backslash at:
-----BEGIN CERTIFICATE-----\r

and:
\r-----END CERTIFICATE-----

and it should work properly, the rest looks fine

**Comment by pinnaclebet** [comment]
lol, 2h lifetime for debugging well spent...I guess we have all been there.

Thank you
