### ISSUE TITLE
Api Docs incomplete

### ISSUE THREAD

**Issue by zabeloliver** [BoschSmartHome/bosch-shc-api-docs#76]
Hi, 
I'm currently exploring the API and want to create an Application. Unfortunately, the API Docs seems to be incomplete. An example would be the `ThermostatSupportedControlMode` Service which is present in the "roomClimateControl" but does not exists in the Docs. 
Anbohre Example is the "Messages" scheme. `MessageCode.name` and `MessageCode.category` are not further specified. It would be good to have the ENUMS to be able to react to the messages.

Is it possible, to get the full API Specs somewhere?

Thanks!
Best regards, 
Oli

**Comment by sebastianharder** [comment]
Hi @zabeloliver,

we are intentionally not publishing all parts of the API. Our focus is on controlling and reading devices, device states, scenarios, etc.

If you have special requests, feel free to let us know (with examples of use) and we might consider adding them to the public API.

Best regards,
Sebastian
