### ISSUE TITLE
Support for API version 2.x dropped in July 2023

### ISSUE THREAD

**Issue by sebastianharder** [BoschSmartHome/bosch-shc-api-docs#80]
In July the Bosch Smart Home controllers will receive an update to version 10.16, which will no longer support API 2.x. Open-source projects using the public SHC REST API must update the "api-version" header in their REST requests to "3.0" or higher, otherwise they can no longer access the SHC with version 10.16 installed.

**Comment by david-pace** [comment]
Is there a summary of changes between 2.1 and 3.0 available? Are there any incompatible changes (I suppose so because it is a major version change)?

**Comment by sebastianharder** [comment]
@david-pace please refer to the changelog: https://github.com/BoschSmartHome/bosch-shc-api-docs/blob/master/CHANGELOG.md

**Comment by sebastianharder** [comment]
Looks like the major open source projects have migrated to API 3.x. Closing.
