### ISSUE TITLE
Stop tilt of Blinds Control (ShutterControl II)

### ISSUE THREAD

**Issue by tschamm** [BoschSmartHome/bosch-shc-api-docs#87]
Dear Bosch team,
I'm implementing support for Blind control of the `ShutterControl II` device. Setting tilt angle is clear, but I'm missing the documentation how to stop the tilt in the current position in the `BlindsControl` service. The function is available in the Bosch App, so maybe this is also exposed via API? The `ShutterControl` service is exposing the operationState which can be set to STOPPED. Is there an equivalent available for the Blinds control?
Best, Thomas

**Comment by jakobgoerke** [comment]
Hi @tschamm i just created a quick debug script here: https://github.com/jakobgoerke/bosch-shc-debug

You just need to run it and trigger the functionality in the app itself, then you would be presented with the operationState (and more) of the device that was triggered.

I also included a readme to set it up, hope that helps.

**Comment by tschamm** [comment]
Bad thing, I do not own that device (Micromodule blind) myself, this is why I cannot test it out. 
The script is helpful for long polling, I have the same functionality in python (much more complicated, though...).

**Comment by jakobgoerke** [comment]
Ah i see ... well sure then this does not help at all :) I also don't own that device currently, lets hope for an official reply then.

**Comment by sebastianharder** [comment]
Hi @tschamm,
there is indeed a REST API to stop shutter/blinds movement:

`PUT /smarthome/shading/shutters/<deviceId>/stop`

Hope, this helps!

**Comment by sebastianharder** [comment]
If you want to move blinds to another level but keep the current angle, you should use the `BlindsSceneControl` state, which first moves the blinds to the desired level and then turns the tilts to the right angle.

**Comment by tschamm** [comment]
Hi @sebastianharder 
I'm missing a body for the PUT command, or should it be a POST?

**Comment by sebastianharder** [comment]
Hi @tschamm,
just checked it: empty body is fine.
