### ISSUE TITLE
Bringing SHC II into pairing mode

### ISSUE THREAD

**Issue by GruberGotHacked** [BoschSmartHome/bosch-shc-api-docs#90]
First of all, thank you for the great work on this project.

I struggled with `SSL warning number 42` and couldn't get it to work until I realized it makes a difference how long you press the button on the SHC. A long press on the button causes the LED to flash, but doesn't activate pairing mode. A short press made it happen. 

Could you please add this info into your documentation.

**Comment by sebastianharder** [comment]
@GruberGotHacked, I updated the README in 9090805. Is there another place where this information is missing from your point of view?

**Comment by GruberGotHacked** [comment]
Should be fine now, thanks
